### ISSUE TITLE
Mac 安装 Wireguard 的 2 个问题

### ISSUE THREAD

**Issue by 117503445** [alanwei43/alanwei43.github.io#1]
https://blog.alanwei.com/blog/2021/03/04/mac-install-wireguard/

二. 配置 WireGurad 客户端 wiregurad 拼错了

启动 WireGuard 应该是 sudo wg-quick up wg0

**Comment by alanwei43** [comment]
> https://blog.alanwei.com/blog/2021/03/04/mac-install-wireguard/
> 
> 二. 配置 WireGurad 客户端 wiregurad 拼错了
> 
> 启动 WireGuard 应该是 sudo wg-quick up wg0

已经更正，多谢提醒~
